export type Byte = [boolean, boolean, boolean, boolean, boolean, boolean, boolean, boolean];

export type ByteToAsciiChar<T extends Byte>
    = T extends [false, false, false, false, false, false, false, false] ? '\0'
    : T extends [false, false, false, false, false, false, false, true] ? '\x01'
    : T extends [false, false, false, false, false, false, true, false] ? '\x02'
    : T extends [false, false, false, false, false, false, true, true] ? '\x03'
    : T extends [false, false, false, false, false, true, false, false] ? '\x04'
    : T extends [false, false, false, false, false, true, false, true] ? '\x05'
    : T extends [false, false, false, false, false, true, true, false] ? '\x06'
    : T extends [false, false, false, false, false, true, true, true] ? '\x07'
    : T extends [false, false, false, false, true, false, false, false] ? '\x08'
    : T extends [false, false, false, false, true, false, false, true] ? '\x09'
    : T extends [false, false, false, false, true, false, true, false] ? '\x0A'
    : T extends [false, false, false, false, true, false, true, true] ? '\x0B'
    : T extends [false, false, false, false, true, true, false, false] ? '\x0C'
    : T extends [false, false, false, false, true, true, false, true] ? '\x0D'
    : T extends [false, false, false, false, true, true, true, false] ? '\x0E'
    : T extends [false, false, false, false, true, true, true, true] ? '\x0F'
    : T extends [false, false, false, true, false, false, false, false] ? '\x10'
    : T extends [false, false, false, true, false, false, false, true] ? '\x11'
    : T extends [false, false, false, true, false, false, true, false] ? '\x12'
    : T extends [false, false, false, true, false, false, true, true] ? '\x13'
    : T extends [false, false, false, true, false, true, false, false] ? '\x14'
    : T extends [false, false, false, true, false, true, false, true] ? '\x15'
    : T extends [false, false, false, true, false, true, true, false] ? '\x16'
    : T extends [false, false, false, true, false, true, true, true] ? '\x17'
    : T extends [false, false, false, true, true, false, false, false] ? '\x18'
    : T extends [false, false, false, true, true, false, false, true] ? '\x19'
    : T extends [false, false, false, true, true, false, true, false] ? '\x1A'
    : T extends [false, false, false, true, true, false, true, true] ? '\x1B'
    : T extends [false, false, false, true, true, true, false, false] ? '\x1C'
    : T extends [false, false, false, true, true, true, false, true] ? '\x1D'
    : T extends [false, false, false, true, true, true, true, false] ? '\x1E'
    : T extends [false, false, false, true, true, true, true, true] ? '\x1F'
    : T extends [false, false, true, false, false, false, false, false] ? '\x20'
    : T extends [false, false, true, false, false, false, false, true] ? '\x21'
    : T extends [false, false, true, false, false, false, true, false] ? '\x22'
    : T extends [false, false, true, false, false, false, true, true] ? '\x23'
    : T extends [false, false, true, false, false, true, false, false] ? '\x24'
    : T extends [false, false, true, false, false, true, false, true] ? '\x25'
    : T extends [false, false, true, false, false, true, true, false] ? '\x26'
    : T extends [false, false, true, false, false, true, true, true] ? '\x27'
    : T extends [false, false, true, false, true, false, false, false] ? '\x28'
    : T extends [false, false, true, false, true, false, false, true] ? '\x29'
    : T extends [false, false, true, false, true, false, true, false] ? '\x2A'
    : T extends [false, false, true, false, true, false, true, true] ? '\x2B'
    : T extends [false, false, true, false, true, true, false, false] ? '\x2C'
    : T extends [false, false, true, false, true, true, false, true] ? '\x2D'
    : T extends [false, false, true, false, true, true, true, false] ? '\x2E'
    : T extends [false, false, true, false, true, true, true, true] ? '\x2F'
    : T extends [false, false, true, true, false, false, false, false] ? '\x30'
    : T extends [false, false, true, true, false, false, false, true] ? '\x31'
    : T extends [false, false, true, true, false, false, true, false] ? '\x32'
    : T extends [false, false, true, true, false, false, true, true] ? '\x33'
    : T extends [false, false, true, true, false, true, false, false] ? '\x34'
    : T extends [false, false, true, true, false, true, false, true] ? '\x35'
    : T extends [false, false, true, true, false, true, true, false] ? '\x36'
    : T extends [false, false, true, true, false, true, true, true] ? '\x37'
    : T extends [false, false, true, true, true, false, false, false] ? '\x38'
    : T extends [false, false, true, true, true, false, false, true] ? '\x39'
    : T extends [false, false, true, true, true, false, true, false] ? '\x3A'
    : T extends [false, false, true, true, true, false, true, true] ? '\x3B'
    : T extends [false, false, true, true, true, true, false, false] ? '\x3C'
    : T extends [false, false, true, true, true, true, false, true] ? '\x3D'
    : T extends [false, false, true, true, true, true, true, false] ? '\x3E'
    : T extends [false, false, true, true, true, true, true, true] ? '\x3F'
    : T extends [false, true, false, false, false, false, false, false] ? '\x40'
    : T extends [false, true, false, false, false, false, false, true] ? '\x41'
    : T extends [false, true, false, false, false, false, true, false] ? '\x42'
    : T extends [false, true, false, false, false, false, true, true] ? '\x43'
    : T extends [false, true, false, false, false, true, false, false] ? '\x44'
    : T extends [false, true, false, false, false, true, false, true] ? '\x45'
    : T extends [false, true, false, false, false, true, true, false] ? '\x46'
    : T extends [false, true, false, false, false, true, true, true] ? '\x47'
    : T extends [false, true, false, false, true, false, false, false] ? '\x48'
    : T extends [false, true, false, false, true, false, false, true] ? '\x49'
    : T extends [false, true, false, false, true, false, true, false] ? '\x4A'
    : T extends [false, true, false, false, true, false, true, true] ? '\x4B'
    : T extends [false, true, false, false, true, true, false, false] ? '\x4C'
    : T extends [false, true, false, false, true, true, false, true] ? '\x4D'
    : T extends [false, true, false, false, true, true, true, false] ? '\x4E'
    : T extends [false, true, false, false, true, true, true, true] ? '\x4F'
    : T extends [false, true, false, true, false, false, false, false] ? '\x50'
    : T extends [false, true, false, true, false, false, false, true] ? '\x51'
    : T extends [false, true, false, true, false, false, true, false] ? '\x52'
    : T extends [false, true, false, true, false, false, true, true] ? '\x53'
    : T extends [false, true, false, true, false, true, false, false] ? '\x54'
    : T extends [false, true, false, true, false, true, false, true] ? '\x55'
    : T extends [false, true, false, true, false, true, true, false] ? '\x56'
    : T extends [false, true, false, true, false, true, true, true] ? '\x57'
    : T extends [false, true, false, true, true, false, false, false] ? '\x58'
    : T extends [false, true, false, true, true, false, false, true] ? '\x59'
    : T extends [false, true, false, true, true, false, true, false] ? '\x5A'
    : T extends [false, true, false, true, true, false, true, true] ? '\x5B'
    : T extends [false, true, false, true, true, true, false, false] ? '\x5C'
    : T extends [false, true, false, true, true, true, false, true] ? '\x5D'
    : T extends [false, true, false, true, true, true, true, false] ? '\x5E'
    : T extends [false, true, false, true, true, true, true, true] ? '\x5F'
    : T extends [false, true, true, false, false, false, false, false] ? '\x60'
    : T extends [false, true, true, false, false, false, false, true] ? '\x61'
    : T extends [false, true, true, false, false, false, true, false] ? '\x62'
    : T extends [false, true, true, false, false, false, true, true] ? '\x63'
    : T extends [false, true, true, false, false, true, false, false] ? '\x64'
    : T extends [false, true, true, false, false, true, false, true] ? '\x65'
    : T extends [false, true, true, false, false, true, true, false] ? '\x66'
    : T extends [false, true, true, false, false, true, true, true] ? '\x67'
    : T extends [false, true, true, false, true, false, false, false] ? '\x68'
    : T extends [false, true, true, false, true, false, false, true] ? '\x69'
    : T extends [false, true, true, false, true, false, true, false] ? '\x6A'
    : T extends [false, true, true, false, true, false, true, true] ? '\x6B'
    : T extends [false, true, true, false, true, true, false, false] ? '\x6C'
    : T extends [false, true, true, false, true, true, false, true] ? '\x6D'
    : T extends [false, true, true, false, true, true, true, false] ? '\x6E'
    : T extends [false, true, true, false, true, true, true, true] ? '\x6F'
    : T extends [false, true, true, true, false, false, false, false] ? '\x70'
    : T extends [false, true, true, true, false, false, false, true] ? '\x71'
    : T extends [false, true, true, true, false, false, true, false] ? '\x72'
    : T extends [false, true, true, true, false, false, true, true] ? '\x73'
    : T extends [false, true, true, true, false, true, false, false] ? '\x74'
    : T extends [false, true, true, true, false, true, false, true] ? '\x75'
    : T extends [false, true, true, true, false, true, true, false] ? '\x76'
    : T extends [false, true, true, true, false, true, true, true] ? '\x77'
    : T extends [false, true, true, true, true, false, false, false] ? '\x78'
    : T extends [false, true, true, true, true, false, false, true] ? '\x79'
    : T extends [false, true, true, true, true, false, true, false] ? '\x7a'
    : T extends [false, true, true, true, true, false, true, true] ? '\x7b'
    : T extends [false, true, true, true, true, true, false, false] ? '\x7c'
    : T extends [false, true, true, true, true, true, false, true] ? '\x7D'
    : T extends [false, true, true, true, true, true, true, false] ? '\x7E'
    : T extends [false, true, true, true, true, true, true, true] ? '\x7F'
    : '';

export type AsciiCharToByte<T extends string>
    = T extends '\x00' ? [false, false, false, false, false, false, false, false]
    : T extends '\x01' ? [false, false, false, false, false, false, false, true]
    : T extends '\x02' ? [false, false, false, false, false, false, true, false]
    : T extends '\x03' ? [false, false, false, false, false, false, true, true]
    : T extends '\x04' ? [false, false, false, false, false, true, false, false]
    : T extends '\x05' ? [false, false, false, false, false, true, false, true]
    : T extends '\x06' ? [false, false, false, false, false, true, true, false]
    : T extends '\x07' ? [false, false, false, false, false, true, true, true]
    : T extends '\x08' ? [false, false, false, false, true, false, false, false]
    : T extends '\x09' ? [false, false, false, false, true, false, false, true]
    : T extends '\x0A' ? [false, false, false, false, true, false, true, false]
    : T extends '\x0B' ? [false, false, false, false, true, false, true, true]
    : T extends '\x0C' ? [false, false, false, false, true, true, false, false]
    : T extends '\x0D' ? [false, false, false, false, true, true, false, true]
    : T extends '\x0E' ? [false, false, false, false, true, true, true, false]
    : T extends '\x0F' ? [false, false, false, false, true, true, true, true]
    : T extends '\x10' ? [false, false, false, true, false, false, false, false]
    : T extends '\x11' ? [false, false, false, true, false, false, false, true]
    : T extends '\x12' ? [false, false, false, true, false, false, true, false]
    : T extends '\x13' ? [false, false, false, true, false, false, true, true]
    : T extends '\x14' ? [false, false, false, true, false, true, false, false]
    : T extends '\x15' ? [false, false, false, true, false, true, false, true]
    : T extends '\x16' ? [false, false, false, true, false, true, true, false]
    : T extends '\x17' ? [false, false, false, true, false, true, true, true]
    : T extends '\x18' ? [false, false, false, true, true, false, false, false]
    : T extends '\x19' ? [false, false, false, true, true, false, false, true]
    : T extends '\x1A' ? [false, false, false, true, true, false, true, false]
    : T extends '\x1B' ? [false, false, false, true, true, false, true, true]
    : T extends '\x1C' ? [false, false, false, true, true, true, false, false]
    : T extends '\x1D' ? [false, false, false, true, true, true, false, true]
    : T extends '\x1E' ? [false, false, false, true, true, true, true, false]
    : T extends '\x1F' ? [false, false, false, true, true, true, true, true]
    : T extends '\x20' ? [false, false, true, false, false, false, false, false]
    : T extends '\x21' ? [false, false, true, false, false, false, false, true]
    : T extends '\x22' ? [false, false, true, false, false, false, true, false]
    : T extends '\x23' ? [false, false, true, false, false, false, true, true]
    : T extends '\x24' ? [false, false, true, false, false, true, false, false]
    : T extends '\x25' ? [false, false, true, false, false, true, false, true]
    : T extends '\x26' ? [false, false, true, false, false, true, true, false]
    : T extends '\x27' ? [false, false, true, false, false, true, true, true]
    : T extends '\x28' ? [false, false, true, false, true, false, false, false]
    : T extends '\x29' ? [false, false, true, false, true, false, false, true]
    : T extends '\x2A' ? [false, false, true, false, true, false, true, false]
    : T extends '\x2B' ? [false, false, true, false, true, false, true, true]
    : T extends '\x2C' ? [false, false, true, false, true, true, false, false]
    : T extends '\x2D' ? [false, false, true, false, true, true, false, true]
    : T extends '\x2E' ? [false, false, true, false, true, true, true, false]
    : T extends '\x2F' ? [false, false, true, false, true, true, true, true]
    : T extends '\x30' ? [false, false, true, true, false, false, false, false]
    : T extends '\x31' ? [false, false, true, true, false, false, false, true]
    : T extends '\x32' ? [false, false, true, true, false, false, true, false]
    : T extends '\x33' ? [false, false, true, true, false, false, true, true]
    : T extends '\x34' ? [false, false, true, true, false, true, false, false]
    : T extends '\x35' ? [false, false, true, true, false, true, false, true]
    : T extends '\x36' ? [false, false, true, true, false, true, true, false]
    : T extends '\x37' ? [false, false, true, true, false, true, true, true]
    : T extends '\x38' ? [false, false, true, true, true, false, false, false]
    : T extends '\x39' ? [false, false, true, true, true, false, false, true]
    : T extends '\x3A' ? [false, false, true, true, true, false, true, false]
    : T extends '\x3B' ? [false, false, true, true, true, false, true, true]
    : T extends '\x3C' ? [false, false, true, true, true, true, false, false]
    : T extends '\x3D' ? [false, false, true, true, true, true, false, true]
    : T extends '\x3E' ? [false, false, true, true, true, true, true, false]
    : T extends '\x3F' ? [false, false, true, true, true, true, true, true]
    : T extends '\x40' ? [false, true, false, false, false, false, false, false]
    : T extends '\x41' ? [false, true, false, false, false, false, false, true]
    : T extends '\x42' ? [false, true, false, false, false, false, true, false]
    : T extends '\x43' ? [false, true, false, false, false, false, true, true]
    : T extends '\x44' ? [false, true, false, false, false, true, false, false]
    : T extends '\x45' ? [false, true, false, false, false, true, false, true]
    : T extends '\x46' ? [false, true, false, false, false, true, true, false]
    : T extends '\x47' ? [false, true, false, false, false, true, true, true]
    : T extends '\x48' ? [false, true, false, false, true, false, false, false]
    : T extends '\x49' ? [false, true, false, false, true, false, false, true]
    : T extends '\x4A' ? [false, true, false, false, true, false, true, false]
    : T extends '\x4B' ? [false, true, false, false, true, false, true, true]
    : T extends '\x4C' ? [false, true, false, false, true, true, false, false]
    : T extends '\x4D' ? [false, true, false, false, true, true, false, true]
    : T extends '\x4E' ? [false, true, false, false, true, true, true, false]
    : T extends '\x4F' ? [false, true, false, false, true, true, true, true]
    : T extends '\x50' ? [false, true, false, true, false, false, false, false]
    : T extends '\x51' ? [false, true, false, true, false, false, false, true]
    : T extends '\x52' ? [false, true, false, true, false, false, true, false]
    : T extends '\x53' ? [false, true, false, true, false, false, true, true]
    : T extends '\x54' ? [false, true, false, true, false, true, false, false]
    : T extends '\x55' ? [false, true, false, true, false, true, false, true]
    : T extends '\x56' ? [false, true, false, true, false, true, true, false]
    : T extends '\x57' ? [false, true, false, true, false, true, true, true]
    : T extends '\x58' ? [false, true, false, true, true, false, false, false]
    : T extends '\x59' ? [false, true, false, true, true, false, false, true]
    : T extends '\x5A' ? [false, true, false, true, true, false, true, false]
    : T extends '\x5B' ? [false, true, false, true, true, false, true, true]
    : T extends '\x5C' ? [false, true, false, true, true, true, false, false]
    : T extends '\x5D' ? [false, true, false, true, true, true, false, true]
    : T extends '\x5E' ? [false, true, false, true, true, true, true, false]
    : T extends '\x5F' ? [false, true, false, true, true, true, true, true]
    : T extends '\x60' ? [false, true, true, false, false, false, false, false]
    : T extends '\x61' ? [false, true, true, false, false, false, false, true]
    : T extends '\x62' ? [false, true, true, false, false, false, true, false]
    : T extends '\x63' ? [false, true, true, false, false, false, true, true]
    : T extends '\x64' ? [false, true, true, false, false, true, false, false]
    : T extends '\x65' ? [false, true, true, false, false, true, false, true]
    : T extends '\x66' ? [false, true, true, false, false, true, true, false]
    : T extends '\x67' ? [false, true, true, false, false, true, true, true]
    : T extends '\x68' ? [false, true, true, false, true, false, false, false]
    : T extends '\x69' ? [false, true, true, false, true, false, false, true]
    : T extends '\x6A' ? [false, true, true, false, true, false, true, false]
    : T extends '\x6B' ? [false, true, true, false, true, false, true, true]
    : T extends '\x6C' ? [false, true, true, false, true, true, false, false]
    : T extends '\x6D' ? [false, true, true, false, true, true, false, true]
    : T extends '\x6E' ? [false, true, true, false, true, true, true, false]
    : T extends '\x6F' ? [false, true, true, false, true, true, true, true]
    : T extends '\x70' ? [false, true, true, true, false, false, false, false]
    : T extends '\x71' ? [false, true, true, true, false, false, false, true]
    : T extends '\x72' ? [false, true, true, true, false, false, true, false]
    : T extends '\x73' ? [false, true, true, true, false, false, true, true]
    : T extends '\x74' ? [false, true, true, true, false, true, false, false]
    : T extends '\x75' ? [false, true, true, true, false, true, false, true]
    : T extends '\x76' ? [false, true, true, true, false, true, true, false]
    : T extends '\x77' ? [false, true, true, true, false, true, true, true]
    : T extends '\x78' ? [false, true, true, true, true, false, false, false]
    : T extends '\x79' ? [false, true, true, true, true, false, false, true]
    : T extends '\x7A' ? [false, true, true, true, true, false, true, false]
    : T extends '\x7B' ? [false, true, true, true, true, false, true, true]
    : T extends '\x7C' ? [false, true, true, true, true, true, false, false]
    : T extends '\x7D' ? [false, true, true, true, true, true, false, true]
    : T extends '\x7E' ? [false, true, true, true, true, true, true, false]
    : T extends '\x7F' ? [false, true, true, true, true, true, true, true]
    : [false, false, false, false, false, false, false, false]