import { Byte } from "../binary";

export type UnsignedNumberToByte<T extends number>
    = T extends 0 ? [false, false, false, false, false, false, false, false]
    : T extends 1 ? [false, false, false, false, false, false, false, true]
    : T extends 2 ? [false, false, false, false, false, false, true, false]
    : T extends 3 ? [false, false, false, false, false, false, true, true]
    : T extends 4 ? [false, false, false, false, false, true, false, false]
    : T extends 5 ? [false, false, false, false, false, true, false, true]
    : T extends 6 ? [false, false, false, false, false, true, true, false]
    : T extends 7 ? [false, false, false, false, false, true, true, true]
    : T extends 8 ? [false, false, false, false, true, false, false, false]
    : T extends 9 ? [false, false, false, false, true, false, false, true]
    : T extends 10 ? [false, false, false, false, true, false, true, false]
    : T extends 11 ? [false, false, false, false, true, false, true, true]
    : T extends 12 ? [false, false, false, false, true, true, false, false]
    : T extends 13 ? [false, false, false, false, true, true, false, true]
    : T extends 14 ? [false, false, false, false, true, true, true, false]
    : T extends 15 ? [false, false, false, false, true, true, true, true]
    : T extends 16 ? [false, false, false, true, false, false, false, false]
    : T extends 17 ? [false, false, false, true, false, false, false, true]
    : T extends 18 ? [false, false, false, true, false, false, true, false]
    : T extends 19 ? [false, false, false, true, false, false, true, true]
    : T extends 20 ? [false, false, false, true, false, true, false, false]
    : T extends 21 ? [false, false, false, true, false, true, false, true]
    : T extends 22 ? [false, false, false, true, false, true, true, false]
    : T extends 23 ? [false, false, false, true, false, true, true, true]
    : T extends 24 ? [false, false, false, true, true, false, false, false]
    : T extends 25 ? [false, false, false, true, true, false, false, true]
    : T extends 26 ? [false, false, false, true, true, false, true, false]
    : T extends 27 ? [false, false, false, true, true, false, true, true]
    : T extends 28 ? [false, false, false, true, true, true, false, false]
    : T extends 29 ? [false, false, false, true, true, true, false, true]
    : T extends 30 ? [false, false, false, true, true, true, true, false]
    : T extends 31 ? [false, false, false, true, true, true, true, true]
    : T extends 32 ? [false, false, true, false, false, false, false, false]
    : T extends 33 ? [false, false, true, false, false, false, false, true]
    : T extends 34 ? [false, false, true, false, false, false, true, false]
    : T extends 35 ? [false, false, true, false, false, false, true, true]
    : T extends 36 ? [false, false, true, false, false, true, false, false]
    : T extends 37 ? [false, false, true, false, false, true, false, true]
    : T extends 38 ? [false, false, true, false, false, true, true, false]
    : T extends 39 ? [false, false, true, false, false, true, true, true]
    : T extends 40 ? [false, false, true, false, true, false, false, false]
    : T extends 41 ? [false, false, true, false, true, false, false, true]
    : T extends 42 ? [false, false, true, false, true, false, true, false]
    : T extends 43 ? [false, false, true, false, true, false, true, true]
    : T extends 44 ? [false, false, true, false, true, true, false, false]
    : T extends 45 ? [false, false, true, false, true, true, false, true]
    : T extends 46 ? [false, false, true, false, true, true, true, false]
    : T extends 47 ? [false, false, true, false, true, true, true, true]
    : T extends 48 ? [false, false, true, true, false, false, false, false]
    : T extends 49 ? [false, false, true, true, false, false, false, true]
    : T extends 50 ? [false, false, true, true, false, false, true, false]
    : T extends 51 ? [false, false, true, true, false, false, true, true]
    : T extends 52 ? [false, false, true, true, false, true, false, false]
    : T extends 53 ? [false, false, true, true, false, true, false, true]
    : T extends 54 ? [false, false, true, true, false, true, true, false]
    : T extends 55 ? [false, false, true, true, false, true, true, true]
    : T extends 56 ? [false, false, true, true, true, false, false, false]
    : T extends 57 ? [false, false, true, true, true, false, false, true]
    : T extends 58 ? [false, false, true, true, true, false, true, false]
    : T extends 59 ? [false, false, true, true, true, false, true, true]
    : T extends 60 ? [false, false, true, true, true, true, false, false]
    : T extends 61 ? [false, false, true, true, true, true, false, true]
    : T extends 62 ? [false, false, true, true, true, true, true, false]
    : T extends 63 ? [false, false, true, true, true, true, true, true]
    : T extends 64 ? [false, true, false, false, false, false, false, false]
    : T extends 65 ? [false, true, false, false, false, false, false, true]
    : T extends 66 ? [false, true, false, false, false, false, true, false]
    : T extends 67 ? [false, true, false, false, false, false, true, true]
    : T extends 68 ? [false, true, false, false, false, true, false, false]
    : T extends 69 ? [false, true, false, false, false, true, false, true]
    : T extends 70 ? [false, true, false, false, false, true, true, false]
    : T extends 71 ? [false, true, false, false, false, true, true, true]
    : T extends 72 ? [false, true, false, false, true, false, false, false]
    : T extends 73 ? [false, true, false, false, true, false, false, true]
    : T extends 74 ? [false, true, false, false, true, false, true, false]
    : T extends 75 ? [false, true, false, false, true, false, true, true]
    : T extends 76 ? [false, true, false, false, true, true, false, false]
    : T extends 77 ? [false, true, false, false, true, true, false, true]
    : T extends 78 ? [false, true, false, false, true, true, true, false]
    : T extends 79 ? [false, true, false, false, true, true, true, true]
    : T extends 80 ? [false, true, false, true, false, false, false, false]
    : T extends 81 ? [false, true, false, true, false, false, false, true]
    : T extends 82 ? [false, true, false, true, false, false, true, false]
    : T extends 83 ? [false, true, false, true, false, false, true, true]
    : T extends 84 ? [false, true, false, true, false, true, false, false]
    : T extends 85 ? [false, true, false, true, false, true, false, true]
    : T extends 86 ? [false, true, false, true, false, true, true, false]
    : T extends 87 ? [false, true, false, true, false, true, true, true]
    : T extends 88 ? [false, true, false, true, true, false, false, false]
    : T extends 89 ? [false, true, false, true, true, false, false, true]
    : T extends 90 ? [false, true, false, true, true, false, true, false]
    : T extends 91 ? [false, true, false, true, true, false, true, true]
    : T extends 92 ? [false, true, false, true, true, true, false, false]
    : T extends 93 ? [false, true, false, true, true, true, false, true]
    : T extends 94 ? [false, true, false, true, true, true, true, false]
    : T extends 95 ? [false, true, false, true, true, true, true, true]
    : T extends 96 ? [false, true, true, false, false, false, false, false]
    : T extends 97 ? [false, true, true, false, false, false, false, true]
    : T extends 98 ? [false, true, true, false, false, false, true, false]
    : T extends 99 ? [false, true, true, false, false, false, true, true]
    : T extends 100 ? [false, true, true, false, false, true, false, false]
    : T extends 101 ? [false, true, true, false, false, true, false, true]
    : T extends 102 ? [false, true, true, false, false, true, true, false]
    : T extends 103 ? [false, true, true, false, false, true, true, true]
    : T extends 104 ? [false, true, true, false, true, false, false, false]
    : T extends 105 ? [false, true, true, false, true, false, false, true]
    : T extends 106 ? [false, true, true, false, true, false, true, false]
    : T extends 107 ? [false, true, true, false, true, false, true, true]
    : T extends 108 ? [false, true, true, false, true, true, false, false]
    : T extends 109 ? [false, true, true, false, true, true, false, true]
    : T extends 110 ? [false, true, true, false, true, true, true, false]
    : T extends 111 ? [false, true, true, false, true, true, true, true]
    : T extends 112 ? [false, true, true, true, false, false, false, false]
    : T extends 113 ? [false, true, true, true, false, false, false, true]
    : T extends 114 ? [false, true, true, true, false, false, true, false]
    : T extends 115 ? [false, true, true, true, false, false, true, true]
    : T extends 116 ? [false, true, true, true, false, true, false, false]
    : T extends 117 ? [false, true, true, true, false, true, false, true]
    : T extends 118 ? [false, true, true, true, false, true, true, false]
    : T extends 119 ? [false, true, true, true, false, true, true, true]
    : T extends 120 ? [false, true, true, true, true, false, false, false]
    : T extends 121 ? [false, true, true, true, true, false, false, true]
    : T extends 122 ? [false, true, true, true, true, false, true, false]
    : T extends 123 ? [false, true, true, true, true, false, true, true]
    : T extends 124 ? [false, true, true, true, true, true, false, false]
    : T extends 125 ? [false, true, true, true, true, true, false, true]
    : T extends 126 ? [false, true, true, true, true, true, true, false]
    : T extends 127 ? [false, true, true, true, true, true, true, true]
    : T extends 128 ? [true, false, false, false, false, false, false, false]
    : T extends 129 ? [true, false, false, false, false, false, false, true]
    : T extends 130 ? [true, false, false, false, false, false, true, false]
    : T extends 131 ? [true, false, false, false, false, false, true, true]
    : T extends 132 ? [true, false, false, false, false, true, false, false]
    : T extends 133 ? [true, false, false, false, false, true, false, true]
    : T extends 134 ? [true, false, false, false, false, true, true, false]
    : T extends 135 ? [true, false, false, false, false, true, true, true]
    : T extends 136 ? [true, false, false, false, true, false, false, false]
    : T extends 137 ? [true, false, false, false, true, false, false, true]
    : T extends 138 ? [true, false, false, false, true, false, true, false]
    : T extends 139 ? [true, false, false, false, true, false, true, true]
    : T extends 140 ? [true, false, false, false, true, true, false, false]
    : T extends 141 ? [true, false, false, false, true, true, false, true]
    : T extends 142 ? [true, false, false, false, true, true, true, false]
    : T extends 143 ? [true, false, false, false, true, true, true, true]
    : T extends 144 ? [true, false, false, true, false, false, false, false]
    : T extends 145 ? [true, false, false, true, false, false, false, true]
    : T extends 146 ? [true, false, false, true, false, false, true, false]
    : T extends 147 ? [true, false, false, true, false, false, true, true]
    : T extends 148 ? [true, false, false, true, false, true, false, false]
    : T extends 149 ? [true, false, false, true, false, true, false, true]
    : T extends 150 ? [true, false, false, true, false, true, true, false]
    : T extends 151 ? [true, false, false, true, false, true, true, true]
    : T extends 152 ? [true, false, false, true, true, false, false, false]
    : T extends 153 ? [true, false, false, true, true, false, false, true]
    : T extends 154 ? [true, false, false, true, true, false, true, false]
    : T extends 155 ? [true, false, false, true, true, false, true, true]
    : T extends 156 ? [true, false, false, true, true, true, false, false]
    : T extends 157 ? [true, false, false, true, true, true, false, true]
    : T extends 158 ? [true, false, false, true, true, true, true, false]
    : T extends 159 ? [true, false, false, true, true, true, true, true]
    : T extends 160 ? [true, false, true, false, false, false, false, false]
    : T extends 161 ? [true, false, true, false, false, false, false, true]
    : T extends 162 ? [true, false, true, false, false, false, true, false]
    : T extends 163 ? [true, false, true, false, false, false, true, true]
    : T extends 164 ? [true, false, true, false, false, true, false, false]
    : T extends 165 ? [true, false, true, false, false, true, false, true]
    : T extends 166 ? [true, false, true, false, false, true, true, false]
    : T extends 167 ? [true, false, true, false, false, true, true, true]
    : T extends 168 ? [true, false, true, false, true, false, false, false]
    : T extends 169 ? [true, false, true, false, true, false, false, true]
    : T extends 170 ? [true, false, true, false, true, false, true, false]
    : T extends 171 ? [true, false, true, false, true, false, true, true]
    : T extends 172 ? [true, false, true, false, true, true, false, false]
    : T extends 173 ? [true, false, true, false, true, true, false, true]
    : T extends 174 ? [true, false, true, false, true, true, true, false]
    : T extends 175 ? [true, false, true, false, true, true, true, true]
    : T extends 176 ? [true, false, true, true, false, false, false, false]
    : T extends 177 ? [true, false, true, true, false, false, false, true]
    : T extends 178 ? [true, false, true, true, false, false, true, false]
    : T extends 179 ? [true, false, true, true, false, false, true, true]
    : T extends 180 ? [true, false, true, true, false, true, false, false]
    : T extends 181 ? [true, false, true, true, false, true, false, true]
    : T extends 182 ? [true, false, true, true, false, true, true, false]
    : T extends 183 ? [true, false, true, true, false, true, true, true]
    : T extends 184 ? [true, false, true, true, true, false, false, false]
    : T extends 185 ? [true, false, true, true, true, false, false, true]
    : T extends 186 ? [true, false, true, true, true, false, true, false]
    : T extends 187 ? [true, false, true, true, true, false, true, true]
    : T extends 188 ? [true, false, true, true, true, true, false, false]
    : T extends 189 ? [true, false, true, true, true, true, false, true]
    : T extends 190 ? [true, false, true, true, true, true, true, false]
    : T extends 191 ? [true, false, true, true, true, true, true, true]
    : T extends 192 ? [true, true, false, false, false, false, false, false]
    : T extends 193 ? [true, true, false, false, false, false, false, true]
    : T extends 194 ? [true, true, false, false, false, false, true, false]
    : T extends 195 ? [true, true, false, false, false, false, true, true]
    : T extends 196 ? [true, true, false, false, false, true, false, false]
    : T extends 197 ? [true, true, false, false, false, true, false, true]
    : T extends 198 ? [true, true, false, false, false, true, true, false]
    : T extends 199 ? [true, true, false, false, false, true, true, true]
    : T extends 200 ? [true, true, false, false, true, false, false, false]
    : T extends 201 ? [true, true, false, false, true, false, false, true]
    : T extends 202 ? [true, true, false, false, true, false, true, false]
    : T extends 203 ? [true, true, false, false, true, false, true, true]
    : T extends 204 ? [true, true, false, false, true, true, false, false]
    : T extends 205 ? [true, true, false, false, true, true, false, true]
    : T extends 206 ? [true, true, false, false, true, true, true, false]
    : T extends 207 ? [true, true, false, false, true, true, true, true]
    : T extends 208 ? [true, true, false, true, false, false, false, false]
    : T extends 209 ? [true, true, false, true, false, false, false, true]
    : T extends 210 ? [true, true, false, true, false, false, true, false]
    : T extends 211 ? [true, true, false, true, false, false, true, true]
    : T extends 212 ? [true, true, false, true, false, true, false, false]
    : T extends 213 ? [true, true, false, true, false, true, false, true]
    : T extends 214 ? [true, true, false, true, false, true, true, false]
    : T extends 215 ? [true, true, false, true, false, true, true, true]
    : T extends 216 ? [true, true, false, true, true, false, false, false]
    : T extends 217 ? [true, true, false, true, true, false, false, true]
    : T extends 218 ? [true, true, false, true, true, false, true, false]
    : T extends 219 ? [true, true, false, true, true, false, true, true]
    : T extends 220 ? [true, true, false, true, true, true, false, false]
    : T extends 221 ? [true, true, false, true, true, true, false, true]
    : T extends 222 ? [true, true, false, true, true, true, true, false]
    : T extends 223 ? [true, true, false, true, true, true, true, true]
    : T extends 224 ? [true, true, true, false, false, false, false, false]
    : T extends 225 ? [true, true, true, false, false, false, false, true]
    : T extends 226 ? [true, true, true, false, false, false, true, false]
    : T extends 227 ? [true, true, true, false, false, false, true, true]
    : T extends 228 ? [true, true, true, false, false, true, false, false]
    : T extends 229 ? [true, true, true, false, false, true, false, true]
    : T extends 230 ? [true, true, true, false, false, true, true, false]
    : T extends 231 ? [true, true, true, false, false, true, true, true]
    : T extends 232 ? [true, true, true, false, true, false, false, false]
    : T extends 233 ? [true, true, true, false, true, false, false, true]
    : T extends 234 ? [true, true, true, false, true, false, true, false]
    : T extends 235 ? [true, true, true, false, true, false, true, true]
    : T extends 236 ? [true, true, true, false, true, true, false, false]
    : T extends 237 ? [true, true, true, false, true, true, false, true]
    : T extends 238 ? [true, true, true, false, true, true, true, false]
    : T extends 239 ? [true, true, true, false, true, true, true, true]
    : T extends 240 ? [true, true, true, true, false, false, false, false]
    : T extends 241 ? [true, true, true, true, false, false, false, true]
    : T extends 242 ? [true, true, true, true, false, false, true, false]
    : T extends 243 ? [true, true, true, true, false, false, true, true]
    : T extends 244 ? [true, true, true, true, false, true, false, false]
    : T extends 245 ? [true, true, true, true, false, true, false, true]
    : T extends 246 ? [true, true, true, true, false, true, true, false]
    : T extends 247 ? [true, true, true, true, false, true, true, true]
    : T extends 248 ? [true, true, true, true, true, false, false, false]
    : T extends 249 ? [true, true, true, true, true, false, false, true]
    : T extends 250 ? [true, true, true, true, true, false, true, false]
    : T extends 251 ? [true, true, true, true, true, false, true, true]
    : T extends 252 ? [true, true, true, true, true, true, false, false]
    : T extends 253 ? [true, true, true, true, true, true, false, true]
    : T extends 254 ? [true, true, true, true, true, true, true, false]
    : T extends 255 ? [true, true, true, true, true, true, true, true]
    : [false, false, false, false, false, false, false, false];

export type ByteToUnsignedNumber<T extends Byte>
    = T extends [false, false, false, false, false, false, false, false] ? 0
    : T extends [false, false, false, false, false, false, false, true] ? 1
    : T extends [false, false, false, false, false, false, true, false] ? 2
    : T extends [false, false, false, false, false, false, true, true] ? 3
    : T extends [false, false, false, false, false, true, false, false] ? 4
    : T extends [false, false, false, false, false, true, false, true] ? 5
    : T extends [false, false, false, false, false, true, true, false] ? 6
    : T extends [false, false, false, false, false, true, true, true] ? 7
    : T extends [false, false, false, false, true, false, false, false] ? 8
    : T extends [false, false, false, false, true, false, false, true] ? 9
    : T extends [false, false, false, false, true, false, true, false] ? 10
    : T extends [false, false, false, false, true, false, true, true] ? 11
    : T extends [false, false, false, false, true, true, false, false] ? 12
    : T extends [false, false, false, false, true, true, false, true] ? 13
    : T extends [false, false, false, false, true, true, true, false] ? 14
    : T extends [false, false, false, false, true, true, true, true] ? 15
    : T extends [false, false, false, true, false, false, false, false] ? 16
    : T extends [false, false, false, true, false, false, false, true] ? 17
    : T extends [false, false, false, true, false, false, true, false] ? 18
    : T extends [false, false, false, true, false, false, true, true] ? 19
    : T extends [false, false, false, true, false, true, false, false] ? 20
    : T extends [false, false, false, true, false, true, false, true] ? 21
    : T extends [false, false, false, true, false, true, true, false] ? 22
    : T extends [false, false, false, true, false, true, true, true] ? 23
    : T extends [false, false, false, true, true, false, false, false] ? 24
    : T extends [false, false, false, true, true, false, false, true] ? 25
    : T extends [false, false, false, true, true, false, true, false] ? 26
    : T extends [false, false, false, true, true, false, true, true] ? 27
    : T extends [false, false, false, true, true, true, false, false] ? 28
    : T extends [false, false, false, true, true, true, false, true] ? 29
    : T extends [false, false, false, true, true, true, true, false] ? 30
    : T extends [false, false, false, true, true, true, true, true] ? 31
    : T extends [false, false, true, false, false, false, false, false] ? 32
    : T extends [false, false, true, false, false, false, false, true] ? 33
    : T extends [false, false, true, false, false, false, true, false] ? 34
    : T extends [false, false, true, false, false, false, true, true] ? 35
    : T extends [false, false, true, false, false, true, false, false] ? 36
    : T extends [false, false, true, false, false, true, false, true] ? 37
    : T extends [false, false, true, false, false, true, true, false] ? 38
    : T extends [false, false, true, false, false, true, true, true] ? 39
    : T extends [false, false, true, false, true, false, false, false] ? 40
    : T extends [false, false, true, false, true, false, false, true] ? 41
    : T extends [false, false, true, false, true, false, true, false] ? 42
    : T extends [false, false, true, false, true, false, true, true] ? 43
    : T extends [false, false, true, false, true, true, false, false] ? 44
    : T extends [false, false, true, false, true, true, false, true] ? 45
    : T extends [false, false, true, false, true, true, true, false] ? 46
    : T extends [false, false, true, false, true, true, true, true] ? 47
    : T extends [false, false, true, true, false, false, false, false] ? 48
    : T extends [false, false, true, true, false, false, false, true] ? 49
    : T extends [false, false, true, true, false, false, true, false] ? 50
    : T extends [false, false, true, true, false, false, true, true] ? 51
    : T extends [false, false, true, true, false, true, false, false] ? 52
    : T extends [false, false, true, true, false, true, false, true] ? 53
    : T extends [false, false, true, true, false, true, true, false] ? 54
    : T extends [false, false, true, true, false, true, true, true] ? 55
    : T extends [false, false, true, true, true, false, false, false] ? 56
    : T extends [false, false, true, true, true, false, false, true] ? 57
    : T extends [false, false, true, true, true, false, true, false] ? 58
    : T extends [false, false, true, true, true, false, true, true] ? 59
    : T extends [false, false, true, true, true, true, false, false] ? 60
    : T extends [false, false, true, true, true, true, false, true] ? 61
    : T extends [false, false, true, true, true, true, true, false] ? 62
    : T extends [false, false, true, true, true, true, true, true] ? 63
    : T extends [false, true, false, false, false, false, false, false] ? 64
    : T extends [false, true, false, false, false, false, false, true] ? 65
    : T extends [false, true, false, false, false, false, true, false] ? 66
    : T extends [false, true, false, false, false, false, true, true] ? 67
    : T extends [false, true, false, false, false, true, false, false] ? 68
    : T extends [false, true, false, false, false, true, false, true] ? 69
    : T extends [false, true, false, false, false, true, true, false] ? 70
    : T extends [false, true, false, false, false, true, true, true] ? 71
    : T extends [false, true, false, false, true, false, false, false] ? 72
    : T extends [false, true, false, false, true, false, false, true] ? 73
    : T extends [false, true, false, false, true, false, true, false] ? 74
    : T extends [false, true, false, false, true, false, true, true] ? 75
    : T extends [false, true, false, false, true, true, false, false] ? 76
    : T extends [false, true, false, false, true, true, false, true] ? 77
    : T extends [false, true, false, false, true, true, true, false] ? 78
    : T extends [false, true, false, false, true, true, true, true] ? 79
    : T extends [false, true, false, true, false, false, false, false] ? 80
    : T extends [false, true, false, true, false, false, false, true] ? 81
    : T extends [false, true, false, true, false, false, true, false] ? 82
    : T extends [false, true, false, true, false, false, true, true] ? 83
    : T extends [false, true, false, true, false, true, false, false] ? 84
    : T extends [false, true, false, true, false, true, false, true] ? 85
    : T extends [false, true, false, true, false, true, true, false] ? 86
    : T extends [false, true, false, true, false, true, true, true] ? 87
    : T extends [false, true, false, true, true, false, false, false] ? 88
    : T extends [false, true, false, true, true, false, false, true] ? 89
    : T extends [false, true, false, true, true, false, true, false] ? 90
    : T extends [false, true, false, true, true, false, true, true] ? 91
    : T extends [false, true, false, true, true, true, false, false] ? 92
    : T extends [false, true, false, true, true, true, false, true] ? 93
    : T extends [false, true, false, true, true, true, true, false] ? 94
    : T extends [false, true, false, true, true, true, true, true] ? 95
    : T extends [false, true, true, false, false, false, false, false] ? 96
    : T extends [false, true, true, false, false, false, false, true] ? 97
    : T extends [false, true, true, false, false, false, true, false] ? 98
    : T extends [false, true, true, false, false, false, true, true] ? 99
    : T extends [false, true, true, false, false, true, false, false] ? 100
    : T extends [false, true, true, false, false, true, false, true] ? 101
    : T extends [false, true, true, false, false, true, true, false] ? 102
    : T extends [false, true, true, false, false, true, true, true] ? 103
    : T extends [false, true, true, false, true, false, false, false] ? 104
    : T extends [false, true, true, false, true, false, false, true] ? 105
    : T extends [false, true, true, false, true, false, true, false] ? 106
    : T extends [false, true, true, false, true, false, true, true] ? 107
    : T extends [false, true, true, false, true, true, false, false] ? 108
    : T extends [false, true, true, false, true, true, false, true] ? 109
    : T extends [false, true, true, false, true, true, true, false] ? 110
    : T extends [false, true, true, false, true, true, true, true] ? 111
    : T extends [false, true, true, true, false, false, false, false] ? 112
    : T extends [false, true, true, true, false, false, false, true] ? 113
    : T extends [false, true, true, true, false, false, true, false] ? 114
    : T extends [false, true, true, true, false, false, true, true] ? 115
    : T extends [false, true, true, true, false, true, false, false] ? 116
    : T extends [false, true, true, true, false, true, false, true] ? 117
    : T extends [false, true, true, true, false, true, true, false] ? 118
    : T extends [false, true, true, true, false, true, true, true] ? 119
    : T extends [false, true, true, true, true, false, false, false] ? 120
    : T extends [false, true, true, true, true, false, false, true] ? 121
    : T extends [false, true, true, true, true, false, true, false] ? 122
    : T extends [false, true, true, true, true, false, true, true] ? 123
    : T extends [false, true, true, true, true, true, false, false] ? 124
    : T extends [false, true, true, true, true, true, false, true] ? 125
    : T extends [false, true, true, true, true, true, true, false] ? 126
    : T extends [false, true, true, true, true, true, true, true] ? 127
    : T extends [true, false, false, false, false, false, false, false] ? 128
    : T extends [true, false, false, false, false, false, false, true] ? 129
    : T extends [true, false, false, false, false, false, true, false] ? 130
    : T extends [true, false, false, false, false, false, true, true] ? 131
    : T extends [true, false, false, false, false, true, false, false] ? 132
    : T extends [true, false, false, false, false, true, false, true] ? 133
    : T extends [true, false, false, false, false, true, true, false] ? 134
    : T extends [true, false, false, false, false, true, true, true] ? 135
    : T extends [true, false, false, false, true, false, false, false] ? 136
    : T extends [true, false, false, false, true, false, false, true] ? 137
    : T extends [true, false, false, false, true, false, true, false] ? 138
    : T extends [true, false, false, false, true, false, true, true] ? 139
    : T extends [true, false, false, false, true, true, false, false] ? 140
    : T extends [true, false, false, false, true, true, false, true] ? 141
    : T extends [true, false, false, false, true, true, true, false] ? 142
    : T extends [true, false, false, false, true, true, true, true] ? 143
    : T extends [true, false, false, true, false, false, false, false] ? 144
    : T extends [true, false, false, true, false, false, false, true] ? 145
    : T extends [true, false, false, true, false, false, true, false] ? 146
    : T extends [true, false, false, true, false, false, true, true] ? 147
    : T extends [true, false, false, true, false, true, false, false] ? 148
    : T extends [true, false, false, true, false, true, false, true] ? 149
    : T extends [true, false, false, true, false, true, true, false] ? 150
    : T extends [true, false, false, true, false, true, true, true] ? 151
    : T extends [true, false, false, true, true, false, false, false] ? 152
    : T extends [true, false, false, true, true, false, false, true] ? 153
    : T extends [true, false, false, true, true, false, true, false] ? 154
    : T extends [true, false, false, true, true, false, true, true] ? 155
    : T extends [true, false, false, true, true, true, false, false] ? 156
    : T extends [true, false, false, true, true, true, false, true] ? 157
    : T extends [true, false, false, true, true, true, true, false] ? 158
    : T extends [true, false, false, true, true, true, true, true] ? 159
    : T extends [true, false, true, false, false, false, false, false] ? 160
    : T extends [true, false, true, false, false, false, false, true] ? 161
    : T extends [true, false, true, false, false, false, true, false] ? 162
    : T extends [true, false, true, false, false, false, true, true] ? 163
    : T extends [true, false, true, false, false, true, false, false] ? 164
    : T extends [true, false, true, false, false, true, false, true] ? 165
    : T extends [true, false, true, false, false, true, true, false] ? 166
    : T extends [true, false, true, false, false, true, true, true] ? 167
    : T extends [true, false, true, false, true, false, false, false] ? 168
    : T extends [true, false, true, false, true, false, false, true] ? 169
    : T extends [true, false, true, false, true, false, true, false] ? 170
    : T extends [true, false, true, false, true, false, true, true] ? 171
    : T extends [true, false, true, false, true, true, false, false] ? 172
    : T extends [true, false, true, false, true, true, false, true] ? 173
    : T extends [true, false, true, false, true, true, true, false] ? 174
    : T extends [true, false, true, false, true, true, true, true] ? 175
    : T extends [true, false, true, true, false, false, false, false] ? 176
    : T extends [true, false, true, true, false, false, false, true] ? 177
    : T extends [true, false, true, true, false, false, true, false] ? 178
    : T extends [true, false, true, true, false, false, true, true] ? 179
    : T extends [true, false, true, true, false, true, false, false] ? 180
    : T extends [true, false, true, true, false, true, false, true] ? 181
    : T extends [true, false, true, true, false, true, true, false] ? 182
    : T extends [true, false, true, true, false, true, true, true] ? 183
    : T extends [true, false, true, true, true, false, false, false] ? 184
    : T extends [true, false, true, true, true, false, false, true] ? 185
    : T extends [true, false, true, true, true, false, true, false] ? 186
    : T extends [true, false, true, true, true, false, true, true] ? 187
    : T extends [true, false, true, true, true, true, false, false] ? 188
    : T extends [true, false, true, true, true, true, false, true] ? 189
    : T extends [true, false, true, true, true, true, true, false] ? 190
    : T extends [true, false, true, true, true, true, true, true] ? 191
    : T extends [true, true, false, false, false, false, false, false] ? 192
    : T extends [true, true, false, false, false, false, false, true] ? 193
    : T extends [true, true, false, false, false, false, true, false] ? 194
    : T extends [true, true, false, false, false, false, true, true] ? 195
    : T extends [true, true, false, false, false, true, false, false] ? 196
    : T extends [true, true, false, false, false, true, false, true] ? 197
    : T extends [true, true, false, false, false, true, true, false] ? 198
    : T extends [true, true, false, false, false, true, true, true] ? 199
    : T extends [true, true, false, false, true, false, false, false] ? 200
    : T extends [true, true, false, false, true, false, false, true] ? 201
    : T extends [true, true, false, false, true, false, true, false] ? 202
    : T extends [true, true, false, false, true, false, true, true] ? 203
    : T extends [true, true, false, false, true, true, false, false] ? 204
    : T extends [true, true, false, false, true, true, false, true] ? 205
    : T extends [true, true, false, false, true, true, true, false] ? 206
    : T extends [true, true, false, false, true, true, true, true] ? 207
    : T extends [true, true, false, true, false, false, false, false] ? 208
    : T extends [true, true, false, true, false, false, false, true] ? 209
    : T extends [true, true, false, true, false, false, true, false] ? 210
    : T extends [true, true, false, true, false, false, true, true] ? 211
    : T extends [true, true, false, true, false, true, false, false] ? 212
    : T extends [true, true, false, true, false, true, false, true] ? 213
    : T extends [true, true, false, true, false, true, true, false] ? 214
    : T extends [true, true, false, true, false, true, true, true] ? 215
    : T extends [true, true, false, true, true, false, false, false] ? 216
    : T extends [true, true, false, true, true, false, false, true] ? 217
    : T extends [true, true, false, true, true, false, true, false] ? 218
    : T extends [true, true, false, true, true, false, true, true] ? 219
    : T extends [true, true, false, true, true, true, false, false] ? 220
    : T extends [true, true, false, true, true, true, false, true] ? 221
    : T extends [true, true, false, true, true, true, true, false] ? 222
    : T extends [true, true, false, true, true, true, true, true] ? 223
    : T extends [true, true, true, false, false, false, false, false] ? 224
    : T extends [true, true, true, false, false, false, false, true] ? 225
    : T extends [true, true, true, false, false, false, true, false] ? 226
    : T extends [true, true, true, false, false, false, true, true] ? 227
    : T extends [true, true, true, false, false, true, false, false] ? 228
    : T extends [true, true, true, false, false, true, false, true] ? 229
    : T extends [true, true, true, false, false, true, true, false] ? 230
    : T extends [true, true, true, false, false, true, true, true] ? 231
    : T extends [true, true, true, false, true, false, false, false] ? 232
    : T extends [true, true, true, false, true, false, false, true] ? 233
    : T extends [true, true, true, false, true, false, true, false] ? 234
    : T extends [true, true, true, false, true, false, true, true] ? 235
    : T extends [true, true, true, false, true, true, false, false] ? 236
    : T extends [true, true, true, false, true, true, false, true] ? 237
    : T extends [true, true, true, false, true, true, true, false] ? 238
    : T extends [true, true, true, false, true, true, true, true] ? 239
    : T extends [true, true, true, true, false, false, false, false] ? 240
    : T extends [true, true, true, true, false, false, false, true] ? 241
    : T extends [true, true, true, true, false, false, true, false] ? 242
    : T extends [true, true, true, true, false, false, true, true] ? 243
    : T extends [true, true, true, true, false, true, false, false] ? 244
    : T extends [true, true, true, true, false, true, false, true] ? 245
    : T extends [true, true, true, true, false, true, true, false] ? 246
    : T extends [true, true, true, true, false, true, true, true] ? 247
    : T extends [true, true, true, true, true, false, false, false] ? 248
    : T extends [true, true, true, true, true, false, false, true] ? 249
    : T extends [true, true, true, true, true, false, true, false] ? 250
    : T extends [true, true, true, true, true, false, true, true] ? 251
    : T extends [true, true, true, true, true, true, false, false] ? 252
    : T extends [true, true, true, true, true, true, false, true] ? 253
    : T extends [true, true, true, true, true, true, true, false] ? 254
    : T extends [true, true, true, true, true, true, true, true] ? 255
    : never